import {
  MousePointer2,
  Hand,
  Minus,
  Circle,
  Square,
  Triangle,
  Activity,
  Ruler,
  Trash2,
  Combine,
  Spline,
  Layers,
  Palette,
  Scan,
  Expand,
  Settings,
  Undo,
  Redo,
  AlignLeft,
  AlignCenterHorizontal,
  AlignRight,
  AlignVerticalJustifyStart,
  AlignCenterVertical,
  AlignVerticalJustifyEnd,
  Type,
  Move,
  RotateCw,
  FilePlus,
  FolderOpen,
  Save,
  FileJson,
  FileSpreadsheet,
  MoveUpRight,
  Plug,
  Lightbulb,
} from 'lucide-react';
import React from 'react';

export const IconMap: Record<string, React.ReactNode> = {
  // Increased size for Line as requested
  Line: <Minus size={24} className="transform -rotate-45" />,
  Arrow: <MoveUpRight size={20} />,
  Polyline: <Activity size={20} />,
  Circle: <Circle size={20} />,
  Arc: <Spline size={20} />,
  Conduit: <Spline size={20} className="transform rotate-90" />,
  Rect: <Square size={20} />,
  Polygon: <Triangle size={20} />,
  Select: <MousePointer2 size={20} />,
  Delete: <Trash2 size={18} />,
  Join: <Combine size={18} />,
  Explode: <Expand size={18} />,
  Measure: <Ruler size={24} />,
  Hand: <Hand size={24} />,
  Layers: <Layers size={16} />,
  Palette: <Palette size={16} />,
  Scan: <Scan size={24} />,
  Settings: <Settings size={20} />,
  Undo: <Undo size={20} />,
  Redo: <Redo size={20} />,
  AlignLeft: <AlignLeft size={18} />,
  AlignCenterH: <AlignCenterHorizontal size={18} />,
  AlignRight: <AlignRight size={18} />,
  AlignTop: <AlignVerticalJustifyStart size={18} />,
  AlignMiddle: <AlignCenterVertical size={18} />,
  AlignBottom: <AlignVerticalJustifyEnd size={18} />,
  Move: <Move size={20} />,
  Rotate: <RotateCw size={20} />,

  // New File Menu Icons
  New: <FilePlus size={20} />,
  Open: <FolderOpen size={20} />,
  Save: <Save size={20} />,
  ExportJSON: <FileJson size={20} />,
  ExportCSV: <FileSpreadsheet size={20} />,
  Text: <Type size={20} />,
  Zap: <MoveUpRight size={20} className="-rotate-45" />,
  Plug: <Plug size={20} />,
  Lightbulb: <Lightbulb size={20} />,
};

export const getIcon = (key: string) => IconMap[key] || <div className="w-4 h-4 bg-red-500" />;
