#pragma once

#undef entityManager_
#undef textSystem_
#undef pickSystem_
#undef viewScale
#undef viewX
#undef viewY
#undef viewWidth
#undef viewHeight
#undef triangleVertices
#undef lineVertices
#undef renderRanges_
#undef snapshotBytes
#undef textQuadsDirty_
#undef renderDirty
#undef snapshotDirty
#undef generation
#undef rebuildAllGeometryCount_
#undef pendingFullRebuild_
#undef lastLoadMs
#undef lastRebuildMs
#undef lastApplyMs
#undef selectionManager_
#undef nextEntityId_
#undef nextLayerId_
#undef historyManager_
#undef eventQueue_
#undef eventHead_
#undef eventTail_
#undef eventCount_
#undef eventOverflowed_
#undef eventOverflowGeneration_
#undef eventBuffer_
#undef pendingEntityChanges_
#undef pendingEntityCreates_
#undef pendingEntityDeletes_
#undef pendingLayerChanges_
#undef pendingDocMask_
#undef pendingSelectionChanged_
#undef pendingOrderChanged_
#undef pendingHistoryChanged_
#undef selectionOutlinePrimitives_
#undef selectionOutlineData_
#undef selectionHandlePrimitives_
#undef selectionHandleData_
#undef snapGuidePrimitives_
#undef snapGuideData_
#undef lastError
#undef interactionSession_
